### ISSUE TITLE
miner unpaid

### ISSUE THREAD

**Issue by Ma3er** [stylesuxx/python-ethermine#1]
Hi, good work, could you add "miner unpaid"?

**Comment by stylesuxx** [comment]
Hey @huskymitch /miner/:miner/currentStats should have a field "unpaid" containing the information you are looking for.

So this should do what you need:

    stats = ethermine.miner_current_stats("address")
    print(stats["unpaid"])

**Comment by Ma3er** [comment]
thank you, that is what I was looking for.
